openapi: 3.2.0
info:
  title: Automated Spreading and Analysis API Key API
  version: 1.3.1
  description: This REST API allows you to interact with the Automated Spreading processing and insights engine.
  x-logo:
    url: https://manual-public-web-static-resources.s3.amazonaws.com/public-api/Moodys-icon.svg
  contact:
    name: Moody's Automated Spreading Customer Support
    email: MA_NMR_Support@moodys.com
security:
- API_Key: []
tags:
- name: API Key
  description: ''
paths:
  /v1/api-key/refresh:
    post:
      operationId: refreshApiKey
      description: Extend the life of the current authorized token by exchanging it for a new one
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiKey'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ApiKey'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ApiKey'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKey'
          description: ''
      tags:
      - API Key
      summary: Refresh Api Key
components:
  schemas:
    ApiKey:
      type: object
      properties:
        refresh_token:
          type: string
          writeOnly: true
          maxLength: 2500
        tenant_id:
          type: string
          writeOnly: true
          maxLength: 50
        access_token:
          type: string
          readOnly: true
        expiration_date:
          type: string
          format: date-time
          readOnly: true
      required:
      - refresh_token
      - tenant_id
  securitySchemes:
    API_Key:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-tagGroups:
- name: Tenant
  tags:
  - Api-Key
  - TenantSettings
- name: Templates
  tags:
  - SpreadingTemplate
  - DscrTemplate
  - GlobalCashflowTemplate
- name: Borrower
  tags:
  - Borrowers
  - Files
  - Loans
  - Requirements
  - Portfolios
- name: Normalized Data
  tags:
  - DataViews
  - Templates
- name: Analysis
  tags:
  - DscrAnalysis
  - GlobalCashflowAnalysis
- name: Events
  tags:
  - Webhooks
- name: Embedded UI
  tags:
  - EmbeddedDocument
  - EmbeddedFinancials
  - EmbeddedDscrAnalysis
  - EmbeddedGlobalCashflowAnalysis
