openapi: 3.2.0
info:
  title: Automated Spreading and Analysis Webhooks API
  version: 1.3.1
  description: This REST API allows you to interact with the Automated Spreading processing and insights engine.
  x-logo:
    url: https://manual-public-web-static-resources.s3.amazonaws.com/public-api/Moodys-icon.svg
  contact:
    name: Moody's Automated Spreading Customer Support
    email: MA_NMR_Support@moodys.com
security:
- API_Key: []
tags:
- name: Webhooks
  description: '## Supported Events


    The following are events you can listen to via webhooks.'
paths:
  /v1/webhook:
    get:
      operationId: listWebhooks
      description: List registered webhooks
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                required:
                - count
                - results
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type:
                    - string
                    - 'null'
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type:
                    - string
                    - 'null'
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Webhook'
          description: ''
      tags:
      - Webhooks
      summary: List webhooks
    post:
      operationId: createWebhook
      description: Register a webhook. This call in idempotent.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Webhook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Webhook'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Webhook'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: ''
      tags:
      - Webhooks
      summary: Create a webhook
  /v1/webhook/{uuid}:
    get:
      operationId: retrieveWebhook
      description: Retrieve a registerted webhook
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
          description: ''
      tags:
      - Webhooks
      summary: Get webhook info
    delete:
      operationId: destroyWebhook
      description: Delete a webhook from Fincura.
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - Webhooks
      summary: Delete a webhook
components:
  schemas:
    Webhook:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        event_type:
          enum:
          - GlobalCashflow.Saved
          - Analysis.Saved
          - DocumentFile.Received
          - DocumentFile.Processing
          - DocumentFile.HumanRequired
          - DocumentFile.SpreadComplete
          - DocumentFile.Error
          - BulkFile.Received
          - BulkFile.Processing
          - BulkFile.Processed
          - BulkFile.Error
          - '*'
          - Template.Changed
          - Borrower.CreatedFromImport
          - CalculatedStatement.Update
          - ForecastedStatement.Update
          - AnnualizedStatement.Update
          type: string
        webhook_url:
          type: string
          format: uri
          maxLength: 2500
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\.(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\]|([a-z¡-\uFFFF0-9](?:[a-z¡-\uFFFF0-9-]{0,61}[a-z¡-\uFFFF0-9])?(?:\\.(?!-)[a-z¡-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z¡-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\s]*)?\\z"
        webhook_method:
          enum:
          - GET
          - POST
          type: string
          default: POST
        external_id:
          type: string
          description: External ID is used to uniquely identify a record from your system in our system. Must be unique across records.
          maxLength: 255
        signing_key:
          type: string
          readOnly: true
          maxLength: 200
      required:
      - event_type
      - webhook_url
  securitySchemes:
    API_Key:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-tagGroups:
- name: Tenant
  tags:
  - Api-Key
  - TenantSettings
- name: Templates
  tags:
  - SpreadingTemplate
  - DscrTemplate
  - GlobalCashflowTemplate
- name: Borrower
  tags:
  - Borrowers
  - Files
  - Loans
  - Requirements
  - Portfolios
- name: Normalized Data
  tags:
  - DataViews
  - Templates
- name: Analysis
  tags:
  - DscrAnalysis
  - GlobalCashflowAnalysis
- name: Events
  tags:
  - Webhooks
- name: Embedded UI
  tags:
  - EmbeddedDocument
  - EmbeddedFinancials
  - EmbeddedDscrAnalysis
  - EmbeddedGlobalCashflowAnalysis
