openapi: 3.2.0
info:
  title: Automated Spreading and Analysis Global Cashflow Template…
  version: 1.3.1
  description: This REST API allows you to interact with the Automated Spreading processing and insights engine.
  x-logo:
    url: https://manual-public-web-static-resources.s3.amazonaws.com/public-api/Moodys-icon.svg
  contact:
    name: Moody's Automated Spreading Customer Support
    email: MA_NMR_Support@moodys.com
security:
- API_Key: []
tags:
- name: GlobalCashflowTemplate
paths:
  /v1/template/global-cashflow:
    get:
      operationId: listGlobalCashflowTemplates
      description: List Global Cashflow templates
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                required:
                - count
                - results
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type:
                    - string
                    - 'null'
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type:
                    - string
                    - 'null'
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/TemplateRead'
          description: ''
      tags:
      - GlobalCashflowTemplate
      summary: List Global Cashflow Templates
components:
  schemas:
    TemplateRead:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        template_type:
          type: string
          readOnly: true
          default: STANDARD
        name:
          type: string
          readOnly: true
        is_default:
          type: boolean
          readOnly: true
        created_date:
          type: string
          format: date-time
          readOnly: true
        active:
          type: boolean
          readOnly: true
  securitySchemes:
    API_Key:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-tagGroups:
- name: Tenant
  tags:
  - Api-Key
  - TenantSettings
- name: Templates
  tags:
  - SpreadingTemplate
  - DscrTemplate
  - GlobalCashflowTemplate
- name: Borrower
  tags:
  - Borrowers
  - Files
  - Loans
  - Requirements
  - Portfolios
- name: Normalized Data
  tags:
  - DataViews
  - Templates
- name: Analysis
  tags:
  - DscrAnalysis
  - GlobalCashflowAnalysis
- name: Events
  tags:
  - Webhooks
- name: Embedded UI
  tags:
  - EmbeddedDocument
  - EmbeddedFinancials
  - EmbeddedDscrAnalysis
  - EmbeddedGlobalCashflowAnalysis
