openapi: 3.2.0
info:
  title: Automated Spreading and Analysis Custom Attributes API
  version: 1.3.1
  description: This REST API allows you to interact with the Automated Spreading processing and insights engine.
  x-logo:
    url: https://manual-public-web-static-resources.s3.amazonaws.com/public-api/Moodys-icon.svg
  contact:
    name: Moody's Automated Spreading Customer Support
    email: MA_NMR_Support@moodys.com
security:
- API_Key: []
tags:
- name: Custom Attributes
paths:
  /v1/custom-attribute-definition:
    get:
      operationId: listCustomAttributeDefinitions
      description: List CustomAttributeDefinition
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                required:
                - count
                - results
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type:
                    - string
                    - 'null'
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type:
                    - string
                    - 'null'
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/CustomAttributeDefinition'
          description: ''
      tags:
      - Custom Attributes
      summary: List CustomAttributeDefinitions
    post:
      operationId: createCustomAttributeDefinition
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomAttributeDefinition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomAttributeDefinition'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomAttributeDefinition'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomAttributeDefinition'
          description: ''
      tags:
      - Custom Attributes
      summary: Create a CustomAttributeDefinition
  /v1/custom-attribute-definition/{uuid}:
    get:
      operationId: retrieveCustomAttributeDefinition
      description: Retrieve a CustomAttributeDefinition
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomAttributeDefinition'
          description: ''
      tags:
      - Custom Attributes
      summary: Get CustomAttributeDefinition info
    delete:
      operationId: destroyCustomAttributeDefinition
      description: Delete a CustomAttributeDefinition.
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - Custom Attributes
      summary: Delete a CustomAttributeDefinition
components:
  schemas:
    CustomAttributeDefinition:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 50
        key:
          type: string
          readOnly: true
        description:
          type:
          - string
          - 'null'
        record_type:
          enum:
          - DocumentFile
          - Borrower
          - Loan
          type: string
        attribute_type:
          enum:
          - STRING
          - BOOLEAN
          - NUMBER
          type: string
        required:
          type: boolean
      required:
      - name
      - record_type
  securitySchemes:
    API_Key:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-tagGroups:
- name: Tenant
  tags:
  - Api-Key
  - TenantSettings
- name: Templates
  tags:
  - SpreadingTemplate
  - DscrTemplate
  - GlobalCashflowTemplate
- name: Borrower
  tags:
  - Borrowers
  - Files
  - Loans
  - Requirements
  - Portfolios
- name: Normalized Data
  tags:
  - DataViews
  - Templates
- name: Analysis
  tags:
  - DscrAnalysis
  - GlobalCashflowAnalysis
- name: Events
  tags:
  - Webhooks
- name: Embedded UI
  tags:
  - EmbeddedDocument
  - EmbeddedFinancials
  - EmbeddedDscrAnalysis
  - EmbeddedGlobalCashflowAnalysis
